
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fabricio 
  password: PostgreSQL_Role_Password


development:
  <<: *default
  database: app_bankline_rails_development

test:
  <<: *default
  database: app_bankline_rails_test


production:
  <<: *default
  database: app_bankline_rails_production
  username: app_bankline_rails
  password: <%= ENV['APP_BANKLINE_RAILS_DATABASE_PASSWORD'] %>
